# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import query_pb2 as query__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryLogs = channel.unary_unary(
                '/query.QueryService/QueryLogs',
                request_serializer=query__pb2.QueryLogsRequest.SerializeToString,
                response_deserializer=query__pb2.QueryLogsResponse.FromString,
                _registered_method=True)
        self.GetLogFacets = channel.unary_unary(
                '/query.QueryService/GetLogFacets',
                request_serializer=query__pb2.GetLogFacetsRequest.SerializeToString,
                response_deserializer=query__pb2.GetLogFacetsResponse.FromString,
                _registered_method=True)
        self.SearchLogs = channel.unary_unary(
                '/query.QueryService/SearchLogs',
                request_serializer=query__pb2.SearchLogsRequest.SerializeToString,
                response_deserializer=query__pb2.SearchLogsResponse.FromString,
                _registered_method=True)
        self.GetLog = channel.unary_unary(
                '/query.QueryService/GetLog',
                request_serializer=query__pb2.GetLogRequest.SerializeToString,
                response_deserializer=query__pb2.GetLogResponse.FromString,
                _registered_method=True)
        self.GetErrorRate = channel.unary_unary(
                '/query.QueryService/GetErrorRate',
                request_serializer=query__pb2.GetErrorRateRequest.SerializeToString,
                response_deserializer=query__pb2.GetErrorRateResponse.FromString,
                _registered_method=True)
        self.GetLogVolume = channel.unary_unary(
                '/query.QueryService/GetLogVolume',
                request_serializer=query__pb2.GetLogVolumeRequest.SerializeToString,
                response_deserializer=query__pb2.GetLogVolumeResponse.FromString,
                _registered_method=True)
        self.GetTopErrors = channel.unary_unary(
                '/query.QueryService/GetTopErrors',
                request_serializer=query__pb2.GetTopErrorsRequest.SerializeToString,
                response_deserializer=query__pb2.GetTopErrorsResponse.FromString,
                _registered_method=True)
        self.GetUsageStats = channel.unary_unary(
                '/query.QueryService/GetUsageStats',
                request_serializer=query__pb2.GetUsageStatsRequest.SerializeToString,
                response_deserializer=query__pb2.GetUsageStatsResponse.FromString,
                _registered_method=True)
        self.GetAggregatedMetrics = channel.unary_unary(
                '/query.QueryService/GetAggregatedMetrics',
                request_serializer=query__pb2.GetAggregatedMetricsRequest.SerializeToString,
                response_deserializer=query__pb2.GetAggregatedMetricsResponse.FromString,
                _registered_method=True)
        self.GetErrorList = channel.unary_unary(
                '/query.QueryService/GetErrorList',
                request_serializer=query__pb2.GetErrorListRequest.SerializeToString,
                response_deserializer=query__pb2.GetErrorListResponse.FromString,
                _registered_method=True)
        self.GetBottleneckMetrics = channel.unary_unary(
                '/query.QueryService/GetBottleneckMetrics',
                request_serializer=query__pb2.GetBottleneckMetricsRequest.SerializeToString,
                response_deserializer=query__pb2.GetBottleneckMetricsResponse.FromString,
                _registered_method=True)
        self.GetBottleneckList = channel.unary_unary(
                '/query.QueryService/GetBottleneckList',
                request_serializer=query__pb2.GetBottleneckListRequest.SerializeToString,
                response_deserializer=query__pb2.GetBottleneckListResponse.FromString,
                _registered_method=True)
        self.GetHealthSummary = channel.unary_unary(
                '/query.QueryService/GetHealthSummary',
                request_serializer=query__pb2.GetHealthSummaryRequest.SerializeToString,
                response_deserializer=query__pb2.GetHealthSummaryResponse.FromString,
                _registered_method=True)
        self.ListErrorGroups = channel.unary_unary(
                '/query.QueryService/ListErrorGroups',
                request_serializer=query__pb2.ListErrorGroupsRequest.SerializeToString,
                response_deserializer=query__pb2.ListErrorGroupsResponse.FromString,
                _registered_method=True)
        self.GetErrorGroup = channel.unary_unary(
                '/query.QueryService/GetErrorGroup',
                request_serializer=query__pb2.GetErrorGroupRequest.SerializeToString,
                response_deserializer=query__pb2.GetErrorGroupResponse.FromString,
                _registered_method=True)
        self.UpdateErrorGroupStatus = channel.unary_unary(
                '/query.QueryService/UpdateErrorGroupStatus',
                request_serializer=query__pb2.UpdateErrorGroupStatusRequest.SerializeToString,
                response_deserializer=query__pb2.UpdateErrorGroupStatusResponse.FromString,
                _registered_method=True)
        self.AssignErrorGroup = channel.unary_unary(
                '/query.QueryService/AssignErrorGroup',
                request_serializer=query__pb2.AssignErrorGroupRequest.SerializeToString,
                response_deserializer=query__pb2.AssignErrorGroupResponse.FromString,
                _registered_method=True)
        self.GetTrace = channel.unary_unary(
                '/query.QueryService/GetTrace',
                request_serializer=query__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=query__pb2.GetTraceResponse.FromString,
                _registered_method=True)
        self.ListTraces = channel.unary_unary(
                '/query.QueryService/ListTraces',
                request_serializer=query__pb2.ListTracesRequest.SerializeToString,
                response_deserializer=query__pb2.ListTracesResponse.FromString,
                _registered_method=True)
        self.GetSpanLatency = channel.unary_unary(
                '/query.QueryService/GetSpanLatency',
                request_serializer=query__pb2.GetSpanLatencyRequest.SerializeToString,
                response_deserializer=query__pb2.GetSpanLatencyResponse.FromString,
                _registered_method=True)
        self.GetMetricSeries = channel.unary_unary(
                '/query.QueryService/GetMetricSeries',
                request_serializer=query__pb2.GetMetricSeriesRequest.SerializeToString,
                response_deserializer=query__pb2.GetMetricSeriesResponse.FromString,
                _registered_method=True)
        self.QueryMetrics = channel.unary_unary(
                '/query.QueryService/QueryMetrics',
                request_serializer=query__pb2.QueryMetricsRequest.SerializeToString,
                response_deserializer=query__pb2.QueryMetricsResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogFacets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregatedMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBottleneckMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBottleneckList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealthSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListErrorGroups(self, request, context):
        """Error group workflow (resolve/ignore/mute/reopen, assignment)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateErrorGroupStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignErrorGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrace(self, request, context):
        """Distributed tracing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpanLatency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetricSeries(self, request, context):
        """Metric points
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLogs,
                    request_deserializer=query__pb2.QueryLogsRequest.FromString,
                    response_serializer=query__pb2.QueryLogsResponse.SerializeToString,
            ),
            'GetLogFacets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogFacets,
                    request_deserializer=query__pb2.GetLogFacetsRequest.FromString,
                    response_serializer=query__pb2.GetLogFacetsResponse.SerializeToString,
            ),
            'SearchLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchLogs,
                    request_deserializer=query__pb2.SearchLogsRequest.FromString,
                    response_serializer=query__pb2.SearchLogsResponse.SerializeToString,
            ),
            'GetLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLog,
                    request_deserializer=query__pb2.GetLogRequest.FromString,
                    response_serializer=query__pb2.GetLogResponse.SerializeToString,
            ),
            'GetErrorRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorRate,
                    request_deserializer=query__pb2.GetErrorRateRequest.FromString,
                    response_serializer=query__pb2.GetErrorRateResponse.SerializeToString,
            ),
            'GetLogVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogVolume,
                    request_deserializer=query__pb2.GetLogVolumeRequest.FromString,
                    response_serializer=query__pb2.GetLogVolumeResponse.SerializeToString,
            ),
            'GetTopErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopErrors,
                    request_deserializer=query__pb2.GetTopErrorsRequest.FromString,
                    response_serializer=query__pb2.GetTopErrorsResponse.SerializeToString,
            ),
            'GetUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageStats,
                    request_deserializer=query__pb2.GetUsageStatsRequest.FromString,
                    response_serializer=query__pb2.GetUsageStatsResponse.SerializeToString,
            ),
            'GetAggregatedMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregatedMetrics,
                    request_deserializer=query__pb2.GetAggregatedMetricsRequest.FromString,
                    response_serializer=query__pb2.GetAggregatedMetricsResponse.SerializeToString,
            ),
            'GetErrorList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorList,
                    request_deserializer=query__pb2.GetErrorListRequest.FromString,
                    response_serializer=query__pb2.GetErrorListResponse.SerializeToString,
            ),
            'GetBottleneckMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBottleneckMetrics,
                    request_deserializer=query__pb2.GetBottleneckMetricsRequest.FromString,
                    response_serializer=query__pb2.GetBottleneckMetricsResponse.SerializeToString,
            ),
            'GetBottleneckList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBottleneckList,
                    request_deserializer=query__pb2.GetBottleneckListRequest.FromString,
                    response_serializer=query__pb2.GetBottleneckListResponse.SerializeToString,
            ),
            'GetHealthSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthSummary,
                    request_deserializer=query__pb2.GetHealthSummaryRequest.FromString,
                    response_serializer=query__pb2.GetHealthSummaryResponse.SerializeToString,
            ),
            'ListErrorGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListErrorGroups,
                    request_deserializer=query__pb2.ListErrorGroupsRequest.FromString,
                    response_serializer=query__pb2.ListErrorGroupsResponse.SerializeToString,
            ),
            'GetErrorGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorGroup,
                    request_deserializer=query__pb2.GetErrorGroupRequest.FromString,
                    response_serializer=query__pb2.GetErrorGroupResponse.SerializeToString,
            ),
            'UpdateErrorGroupStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateErrorGroupStatus,
                    request_deserializer=query__pb2.UpdateErrorGroupStatusRequest.FromString,
                    response_serializer=query__pb2.UpdateErrorGroupStatusResponse.SerializeToString,
            ),
            'AssignErrorGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignErrorGroup,
                    request_deserializer=query__pb2.AssignErrorGroupRequest.FromString,
                    response_serializer=query__pb2.AssignErrorGroupResponse.SerializeToString,
            ),
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=query__pb2.GetTraceRequest.FromString,
                    response_serializer=query__pb2.GetTraceResponse.SerializeToString,
            ),
            'ListTraces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTraces,
                    request_deserializer=query__pb2.ListTracesRequest.FromString,
                    response_serializer=query__pb2.ListTracesResponse.SerializeToString,
            ),
            'GetSpanLatency': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpanLatency,
                    request_deserializer=query__pb2.GetSpanLatencyRequest.FromString,
                    response_serializer=query__pb2.GetSpanLatencyResponse.SerializeToString,
            ),
            'GetMetricSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetricSeries,
                    request_deserializer=query__pb2.GetMetricSeriesRequest.FromString,
                    response_serializer=query__pb2.GetMetricSeriesResponse.SerializeToString,
            ),
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=query__pb2.QueryMetricsRequest.FromString,
                    response_serializer=query__pb2.QueryMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'query.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('query.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/QueryLogs',
            query__pb2.QueryLogsRequest.SerializeToString,
            query__pb2.QueryLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogFacets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetLogFacets',
            query__pb2.GetLogFacetsRequest.SerializeToString,
            query__pb2.GetLogFacetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/SearchLogs',
            query__pb2.SearchLogsRequest.SerializeToString,
            query__pb2.SearchLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetLog',
            query__pb2.GetLogRequest.SerializeToString,
            query__pb2.GetLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetErrorRate',
            query__pb2.GetErrorRateRequest.SerializeToString,
            query__pb2.GetErrorRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetLogVolume',
            query__pb2.GetLogVolumeRequest.SerializeToString,
            query__pb2.GetLogVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetTopErrors',
            query__pb2.GetTopErrorsRequest.SerializeToString,
            query__pb2.GetTopErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetUsageStats',
            query__pb2.GetUsageStatsRequest.SerializeToString,
            query__pb2.GetUsageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregatedMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetAggregatedMetrics',
            query__pb2.GetAggregatedMetricsRequest.SerializeToString,
            query__pb2.GetAggregatedMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetErrorList',
            query__pb2.GetErrorListRequest.SerializeToString,
            query__pb2.GetErrorListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBottleneckMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetBottleneckMetrics',
            query__pb2.GetBottleneckMetricsRequest.SerializeToString,
            query__pb2.GetBottleneckMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBottleneckList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetBottleneckList',
            query__pb2.GetBottleneckListRequest.SerializeToString,
            query__pb2.GetBottleneckListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealthSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetHealthSummary',
            query__pb2.GetHealthSummaryRequest.SerializeToString,
            query__pb2.GetHealthSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListErrorGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/ListErrorGroups',
            query__pb2.ListErrorGroupsRequest.SerializeToString,
            query__pb2.ListErrorGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetErrorGroup',
            query__pb2.GetErrorGroupRequest.SerializeToString,
            query__pb2.GetErrorGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateErrorGroupStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/UpdateErrorGroupStatus',
            query__pb2.UpdateErrorGroupStatusRequest.SerializeToString,
            query__pb2.UpdateErrorGroupStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignErrorGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/AssignErrorGroup',
            query__pb2.AssignErrorGroupRequest.SerializeToString,
            query__pb2.AssignErrorGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetTrace',
            query__pb2.GetTraceRequest.SerializeToString,
            query__pb2.GetTraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/ListTraces',
            query__pb2.ListTracesRequest.SerializeToString,
            query__pb2.ListTracesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpanLatency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetSpanLatency',
            query__pb2.GetSpanLatencyRequest.SerializeToString,
            query__pb2.GetSpanLatencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetricSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/GetMetricSeries',
            query__pb2.GetMetricSeriesRequest.SerializeToString,
            query__pb2.GetMetricSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query.QueryService/QueryMetrics',
            query__pb2.QueryMetricsRequest.SerializeToString,
            query__pb2.QueryMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
