# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/auth.AuthService/Register',
                request_serializer=auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=auth__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/auth.AuthService/RefreshToken',
                request_serializer=auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/auth.AuthService/GetAccount',
                request_serializer=auth__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.UpdateAccountName = channel.unary_unary(
                '/auth.AuthService/UpdateAccountName',
                request_serializer=auth__pb2.UpdateAccountNameRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateAccountNameResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/auth.AuthService/ChangePassword',
                request_serializer=auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=auth__pb2.ChangePasswordResponse.FromString,
                _registered_method=True)
        self.GetNotificationPreferences = channel.unary_unary(
                '/auth.AuthService/GetNotificationPreferences',
                request_serializer=auth__pb2.GetNotificationPreferencesRequest.SerializeToString,
                response_deserializer=auth__pb2.GetNotificationPreferencesResponse.FromString,
                _registered_method=True)
        self.UpdateNotificationPreferences = channel.unary_unary(
                '/auth.AuthService/UpdateNotificationPreferences',
                request_serializer=auth__pb2.UpdateNotificationPreferencesRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateNotificationPreferencesResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/auth.AuthService/CreateProject',
                request_serializer=auth__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.GetProjects = channel.unary_unary(
                '/auth.AuthService/GetProjects',
                request_serializer=auth__pb2.GetProjectsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetProjectsResponse.FromString,
                _registered_method=True)
        self.GetProjectById = channel.unary_unary(
                '/auth.AuthService/GetProjectById',
                request_serializer=auth__pb2.GetProjectByIdRequest.SerializeToString,
                response_deserializer=auth__pb2.GetProjectByIdResponse.FromString,
                _registered_method=True)
        self.GenerateInviteCode = channel.unary_unary(
                '/auth.AuthService/GenerateInviteCode',
                request_serializer=auth__pb2.GenerateInviteCodeRequest.SerializeToString,
                response_deserializer=auth__pb2.GenerateInviteCodeResponse.FromString,
                _registered_method=True)
        self.AcceptInviteCode = channel.unary_unary(
                '/auth.AuthService/AcceptInviteCode',
                request_serializer=auth__pb2.AcceptInviteCodeRequest.SerializeToString,
                response_deserializer=auth__pb2.AcceptInviteCodeResponse.FromString,
                _registered_method=True)
        self.ListProjectMembers = channel.unary_unary(
                '/auth.AuthService/ListProjectMembers',
                request_serializer=auth__pb2.ListProjectMembersRequest.SerializeToString,
                response_deserializer=auth__pb2.ListProjectMembersResponse.FromString,
                _registered_method=True)
        self.RemoveProjectMember = channel.unary_unary(
                '/auth.AuthService/RemoveProjectMember',
                request_serializer=auth__pb2.RemoveProjectMemberRequest.SerializeToString,
                response_deserializer=auth__pb2.RemoveProjectMemberResponse.FromString,
                _registered_method=True)
        self.LeaveProject = channel.unary_unary(
                '/auth.AuthService/LeaveProject',
                request_serializer=auth__pb2.LeaveProjectRequest.SerializeToString,
                response_deserializer=auth__pb2.LeaveProjectResponse.FromString,
                _registered_method=True)
        self.GetProjectRole = channel.unary_unary(
                '/auth.AuthService/GetProjectRole',
                request_serializer=auth__pb2.GetProjectRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.GetProjectRoleResponse.FromString,
                _registered_method=True)
        self.CreateApiKey = channel.unary_unary(
                '/auth.AuthService/CreateApiKey',
                request_serializer=auth__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateApiKeyResponse.FromString,
                _registered_method=True)
        self.ValidateApiKey = channel.unary_unary(
                '/auth.AuthService/ValidateApiKey',
                request_serializer=auth__pb2.ValidateApiKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateApiKeyResponse.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/auth.AuthService/RevokeApiKey',
                request_serializer=auth__pb2.RevokeApiKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.RevokeApiKeyResponse.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/auth.AuthService/ListApiKeys',
                request_serializer=auth__pb2.ListApiKeysRequest.SerializeToString,
                response_deserializer=auth__pb2.ListApiKeysResponse.FromString,
                _registered_method=True)
        self.GetDailyUsage = channel.unary_unary(
                '/auth.AuthService/GetDailyUsage',
                request_serializer=auth__pb2.GetDailyUsageRequest.SerializeToString,
                response_deserializer=auth__pb2.GetDailyUsageResponse.FromString,
                _registered_method=True)
        self.GetDashboardPanels = channel.unary_unary(
                '/auth.AuthService/GetDashboardPanels',
                request_serializer=auth__pb2.GetDashboardPanelsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetDashboardPanelsResponse.FromString,
                _registered_method=True)
        self.CreateDashboardPanel = channel.unary_unary(
                '/auth.AuthService/CreateDashboardPanel',
                request_serializer=auth__pb2.CreateDashboardPanelRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateDashboardPanelResponse.FromString,
                _registered_method=True)
        self.UpdateDashboardPanel = channel.unary_unary(
                '/auth.AuthService/UpdateDashboardPanel',
                request_serializer=auth__pb2.UpdateDashboardPanelRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateDashboardPanelResponse.FromString,
                _registered_method=True)
        self.DeleteDashboardPanel = channel.unary_unary(
                '/auth.AuthService/DeleteDashboardPanel',
                request_serializer=auth__pb2.DeleteDashboardPanelRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteDashboardPanelResponse.FromString,
                _registered_method=True)
        self.ListNotifications = channel.unary_unary(
                '/auth.AuthService/ListNotifications',
                request_serializer=auth__pb2.ListNotificationsRequest.SerializeToString,
                response_deserializer=auth__pb2.ListNotificationsResponse.FromString,
                _registered_method=True)
        self.GetUnreadNotificationCount = channel.unary_unary(
                '/auth.AuthService/GetUnreadNotificationCount',
                request_serializer=auth__pb2.GetUnreadNotificationCountRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUnreadNotificationCountResponse.FromString,
                _registered_method=True)
        self.MarkNotificationRead = channel.unary_unary(
                '/auth.AuthService/MarkNotificationRead',
                request_serializer=auth__pb2.MarkNotificationReadRequest.SerializeToString,
                response_deserializer=auth__pb2.MarkNotificationReadResponse.FromString,
                _registered_method=True)
        self.MarkAllNotificationsRead = channel.unary_unary(
                '/auth.AuthService/MarkAllNotificationsRead',
                request_serializer=auth__pb2.MarkAllNotificationsReadRequest.SerializeToString,
                response_deserializer=auth__pb2.MarkAllNotificationsReadResponse.FromString,
                _registered_method=True)
        self.DeleteNotification = channel.unary_unary(
                '/auth.AuthService/DeleteNotification',
                request_serializer=auth__pb2.DeleteNotificationRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteNotificationResponse.FromString,
                _registered_method=True)
        self.CreateNotification = channel.unary_unary(
                '/auth.AuthService/CreateNotification',
                request_serializer=auth__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateNotificationResponse.FromString,
                _registered_method=True)
        self.ListAlertRules = channel.unary_unary(
                '/auth.AuthService/ListAlertRules',
                request_serializer=auth__pb2.ListAlertRulesRequest.SerializeToString,
                response_deserializer=auth__pb2.ListAlertRulesResponse.FromString,
                _registered_method=True)
        self.GetAlertRule = channel.unary_unary(
                '/auth.AuthService/GetAlertRule',
                request_serializer=auth__pb2.GetAlertRuleRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAlertRuleResponse.FromString,
                _registered_method=True)
        self.CreateAlertRule = channel.unary_unary(
                '/auth.AuthService/CreateAlertRule',
                request_serializer=auth__pb2.CreateAlertRuleRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateAlertRuleResponse.FromString,
                _registered_method=True)
        self.UpdateAlertRule = channel.unary_unary(
                '/auth.AuthService/UpdateAlertRule',
                request_serializer=auth__pb2.UpdateAlertRuleRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateAlertRuleResponse.FromString,
                _registered_method=True)
        self.DeleteAlertRule = channel.unary_unary(
                '/auth.AuthService/DeleteAlertRule',
                request_serializer=auth__pb2.DeleteAlertRuleRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteAlertRuleResponse.FromString,
                _registered_method=True)
        self.ListAlertChannels = channel.unary_unary(
                '/auth.AuthService/ListAlertChannels',
                request_serializer=auth__pb2.ListAlertChannelsRequest.SerializeToString,
                response_deserializer=auth__pb2.ListAlertChannelsResponse.FromString,
                _registered_method=True)
        self.GetAlertChannel = channel.unary_unary(
                '/auth.AuthService/GetAlertChannel',
                request_serializer=auth__pb2.GetAlertChannelRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAlertChannelResponse.FromString,
                _registered_method=True)
        self.CreateAlertChannel = channel.unary_unary(
                '/auth.AuthService/CreateAlertChannel',
                request_serializer=auth__pb2.CreateAlertChannelRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateAlertChannelResponse.FromString,
                _registered_method=True)
        self.UpdateAlertChannel = channel.unary_unary(
                '/auth.AuthService/UpdateAlertChannel',
                request_serializer=auth__pb2.UpdateAlertChannelRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateAlertChannelResponse.FromString,
                _registered_method=True)
        self.DeleteAlertChannel = channel.unary_unary(
                '/auth.AuthService/DeleteAlertChannel',
                request_serializer=auth__pb2.DeleteAlertChannelRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteAlertChannelResponse.FromString,
                _registered_method=True)
        self.GetAlertNotificationPreferences = channel.unary_unary(
                '/auth.AuthService/GetAlertNotificationPreferences',
                request_serializer=auth__pb2.GetAlertNotificationPreferencesRequest.SerializeToString,
                response_deserializer=auth__pb2.GetAlertNotificationPreferencesResponse.FromString,
                _registered_method=True)
        self.UpsertAlertNotificationPreference = channel.unary_unary(
                '/auth.AuthService/UpsertAlertNotificationPreference',
                request_serializer=auth__pb2.UpsertAlertNotificationPreferenceRequest.SerializeToString,
                response_deserializer=auth__pb2.UpsertAlertNotificationPreferenceResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Account operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccountName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotificationPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotificationPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Project operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateInviteCode(self, request, context):
        """Project sharing operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptInviteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProjectMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """API key operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDailyUsage(self, request, context):
        """Usage tracking operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboardPanels(self, request, context):
        """Dashboard panel operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDashboardPanel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDashboardPanel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDashboardPanel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """Notification inbox operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnreadNotificationCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkNotificationRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAllNotificationsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlertRules(self, request, context):
        """Alert rule operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlertRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlertRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlertRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlertChannels(self, request, context):
        """Alert channel operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlertChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlertChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlertChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertNotificationPreferences(self, request, context):
        """Notification preferences (alert-specific)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertAlertNotificationPreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auth__pb2.RegisterRequest.FromString,
                    response_serializer=auth__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginRequest.FromString,
                    response_serializer=auth__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=auth__pb2.GetAccountRequest.FromString,
                    response_serializer=auth__pb2.GetAccountResponse.SerializeToString,
            ),
            'UpdateAccountName': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccountName,
                    request_deserializer=auth__pb2.UpdateAccountNameRequest.FromString,
                    response_serializer=auth__pb2.UpdateAccountNameResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=auth__pb2.ChangePasswordResponse.SerializeToString,
            ),
            'GetNotificationPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotificationPreferences,
                    request_deserializer=auth__pb2.GetNotificationPreferencesRequest.FromString,
                    response_serializer=auth__pb2.GetNotificationPreferencesResponse.SerializeToString,
            ),
            'UpdateNotificationPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotificationPreferences,
                    request_deserializer=auth__pb2.UpdateNotificationPreferencesRequest.FromString,
                    response_serializer=auth__pb2.UpdateNotificationPreferencesResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=auth__pb2.CreateProjectRequest.FromString,
                    response_serializer=auth__pb2.CreateProjectResponse.SerializeToString,
            ),
            'GetProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjects,
                    request_deserializer=auth__pb2.GetProjectsRequest.FromString,
                    response_serializer=auth__pb2.GetProjectsResponse.SerializeToString,
            ),
            'GetProjectById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectById,
                    request_deserializer=auth__pb2.GetProjectByIdRequest.FromString,
                    response_serializer=auth__pb2.GetProjectByIdResponse.SerializeToString,
            ),
            'GenerateInviteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInviteCode,
                    request_deserializer=auth__pb2.GenerateInviteCodeRequest.FromString,
                    response_serializer=auth__pb2.GenerateInviteCodeResponse.SerializeToString,
            ),
            'AcceptInviteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptInviteCode,
                    request_deserializer=auth__pb2.AcceptInviteCodeRequest.FromString,
                    response_serializer=auth__pb2.AcceptInviteCodeResponse.SerializeToString,
            ),
            'ListProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjectMembers,
                    request_deserializer=auth__pb2.ListProjectMembersRequest.FromString,
                    response_serializer=auth__pb2.ListProjectMembersResponse.SerializeToString,
            ),
            'RemoveProjectMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProjectMember,
                    request_deserializer=auth__pb2.RemoveProjectMemberRequest.FromString,
                    response_serializer=auth__pb2.RemoveProjectMemberResponse.SerializeToString,
            ),
            'LeaveProject': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveProject,
                    request_deserializer=auth__pb2.LeaveProjectRequest.FromString,
                    response_serializer=auth__pb2.LeaveProjectResponse.SerializeToString,
            ),
            'GetProjectRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectRole,
                    request_deserializer=auth__pb2.GetProjectRoleRequest.FromString,
                    response_serializer=auth__pb2.GetProjectRoleResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=auth__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=auth__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'ValidateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateApiKey,
                    request_deserializer=auth__pb2.ValidateApiKeyRequest.FromString,
                    response_serializer=auth__pb2.ValidateApiKeyResponse.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=auth__pb2.RevokeApiKeyRequest.FromString,
                    response_serializer=auth__pb2.RevokeApiKeyResponse.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=auth__pb2.ListApiKeysRequest.FromString,
                    response_serializer=auth__pb2.ListApiKeysResponse.SerializeToString,
            ),
            'GetDailyUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyUsage,
                    request_deserializer=auth__pb2.GetDailyUsageRequest.FromString,
                    response_serializer=auth__pb2.GetDailyUsageResponse.SerializeToString,
            ),
            'GetDashboardPanels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardPanels,
                    request_deserializer=auth__pb2.GetDashboardPanelsRequest.FromString,
                    response_serializer=auth__pb2.GetDashboardPanelsResponse.SerializeToString,
            ),
            'CreateDashboardPanel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDashboardPanel,
                    request_deserializer=auth__pb2.CreateDashboardPanelRequest.FromString,
                    response_serializer=auth__pb2.CreateDashboardPanelResponse.SerializeToString,
            ),
            'UpdateDashboardPanel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDashboardPanel,
                    request_deserializer=auth__pb2.UpdateDashboardPanelRequest.FromString,
                    response_serializer=auth__pb2.UpdateDashboardPanelResponse.SerializeToString,
            ),
            'DeleteDashboardPanel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDashboardPanel,
                    request_deserializer=auth__pb2.DeleteDashboardPanelRequest.FromString,
                    response_serializer=auth__pb2.DeleteDashboardPanelResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=auth__pb2.ListNotificationsRequest.FromString,
                    response_serializer=auth__pb2.ListNotificationsResponse.SerializeToString,
            ),
            'GetUnreadNotificationCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnreadNotificationCount,
                    request_deserializer=auth__pb2.GetUnreadNotificationCountRequest.FromString,
                    response_serializer=auth__pb2.GetUnreadNotificationCountResponse.SerializeToString,
            ),
            'MarkNotificationRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkNotificationRead,
                    request_deserializer=auth__pb2.MarkNotificationReadRequest.FromString,
                    response_serializer=auth__pb2.MarkNotificationReadResponse.SerializeToString,
            ),
            'MarkAllNotificationsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAllNotificationsRead,
                    request_deserializer=auth__pb2.MarkAllNotificationsReadRequest.FromString,
                    response_serializer=auth__pb2.MarkAllNotificationsReadResponse.SerializeToString,
            ),
            'DeleteNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNotification,
                    request_deserializer=auth__pb2.DeleteNotificationRequest.FromString,
                    response_serializer=auth__pb2.DeleteNotificationResponse.SerializeToString,
            ),
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=auth__pb2.CreateNotificationRequest.FromString,
                    response_serializer=auth__pb2.CreateNotificationResponse.SerializeToString,
            ),
            'ListAlertRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlertRules,
                    request_deserializer=auth__pb2.ListAlertRulesRequest.FromString,
                    response_serializer=auth__pb2.ListAlertRulesResponse.SerializeToString,
            ),
            'GetAlertRule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertRule,
                    request_deserializer=auth__pb2.GetAlertRuleRequest.FromString,
                    response_serializer=auth__pb2.GetAlertRuleResponse.SerializeToString,
            ),
            'CreateAlertRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlertRule,
                    request_deserializer=auth__pb2.CreateAlertRuleRequest.FromString,
                    response_serializer=auth__pb2.CreateAlertRuleResponse.SerializeToString,
            ),
            'UpdateAlertRule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlertRule,
                    request_deserializer=auth__pb2.UpdateAlertRuleRequest.FromString,
                    response_serializer=auth__pb2.UpdateAlertRuleResponse.SerializeToString,
            ),
            'DeleteAlertRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlertRule,
                    request_deserializer=auth__pb2.DeleteAlertRuleRequest.FromString,
                    response_serializer=auth__pb2.DeleteAlertRuleResponse.SerializeToString,
            ),
            'ListAlertChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlertChannels,
                    request_deserializer=auth__pb2.ListAlertChannelsRequest.FromString,
                    response_serializer=auth__pb2.ListAlertChannelsResponse.SerializeToString,
            ),
            'GetAlertChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertChannel,
                    request_deserializer=auth__pb2.GetAlertChannelRequest.FromString,
                    response_serializer=auth__pb2.GetAlertChannelResponse.SerializeToString,
            ),
            'CreateAlertChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlertChannel,
                    request_deserializer=auth__pb2.CreateAlertChannelRequest.FromString,
                    response_serializer=auth__pb2.CreateAlertChannelResponse.SerializeToString,
            ),
            'UpdateAlertChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlertChannel,
                    request_deserializer=auth__pb2.UpdateAlertChannelRequest.FromString,
                    response_serializer=auth__pb2.UpdateAlertChannelResponse.SerializeToString,
            ),
            'DeleteAlertChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlertChannel,
                    request_deserializer=auth__pb2.DeleteAlertChannelRequest.FromString,
                    response_serializer=auth__pb2.DeleteAlertChannelResponse.SerializeToString,
            ),
            'GetAlertNotificationPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertNotificationPreferences,
                    request_deserializer=auth__pb2.GetAlertNotificationPreferencesRequest.FromString,
                    response_serializer=auth__pb2.GetAlertNotificationPreferencesResponse.SerializeToString,
            ),
            'UpsertAlertNotificationPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertAlertNotificationPreference,
                    request_deserializer=auth__pb2.UpsertAlertNotificationPreferenceRequest.FromString,
                    response_serializer=auth__pb2.UpsertAlertNotificationPreferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Register',
            auth__pb2.RegisterRequest.SerializeToString,
            auth__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Login',
            auth__pb2.LoginRequest.SerializeToString,
            auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RefreshToken',
            auth__pb2.RefreshTokenRequest.SerializeToString,
            auth__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetAccount',
            auth__pb2.GetAccountRequest.SerializeToString,
            auth__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccountName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateAccountName',
            auth__pb2.UpdateAccountNameRequest.SerializeToString,
            auth__pb2.UpdateAccountNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ChangePassword',
            auth__pb2.ChangePasswordRequest.SerializeToString,
            auth__pb2.ChangePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotificationPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetNotificationPreferences',
            auth__pb2.GetNotificationPreferencesRequest.SerializeToString,
            auth__pb2.GetNotificationPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotificationPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateNotificationPreferences',
            auth__pb2.UpdateNotificationPreferencesRequest.SerializeToString,
            auth__pb2.UpdateNotificationPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateProject',
            auth__pb2.CreateProjectRequest.SerializeToString,
            auth__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetProjects',
            auth__pb2.GetProjectsRequest.SerializeToString,
            auth__pb2.GetProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetProjectById',
            auth__pb2.GetProjectByIdRequest.SerializeToString,
            auth__pb2.GetProjectByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateInviteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GenerateInviteCode',
            auth__pb2.GenerateInviteCodeRequest.SerializeToString,
            auth__pb2.GenerateInviteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptInviteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AcceptInviteCode',
            auth__pb2.AcceptInviteCodeRequest.SerializeToString,
            auth__pb2.AcceptInviteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListProjectMembers',
            auth__pb2.ListProjectMembersRequest.SerializeToString,
            auth__pb2.ListProjectMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProjectMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RemoveProjectMember',
            auth__pb2.RemoveProjectMemberRequest.SerializeToString,
            auth__pb2.RemoveProjectMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/LeaveProject',
            auth__pb2.LeaveProjectRequest.SerializeToString,
            auth__pb2.LeaveProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetProjectRole',
            auth__pb2.GetProjectRoleRequest.SerializeToString,
            auth__pb2.GetProjectRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateApiKey',
            auth__pb2.CreateApiKeyRequest.SerializeToString,
            auth__pb2.CreateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateApiKey',
            auth__pb2.ValidateApiKeyRequest.SerializeToString,
            auth__pb2.ValidateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RevokeApiKey',
            auth__pb2.RevokeApiKeyRequest.SerializeToString,
            auth__pb2.RevokeApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListApiKeys',
            auth__pb2.ListApiKeysRequest.SerializeToString,
            auth__pb2.ListApiKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDailyUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetDailyUsage',
            auth__pb2.GetDailyUsageRequest.SerializeToString,
            auth__pb2.GetDailyUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboardPanels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetDashboardPanels',
            auth__pb2.GetDashboardPanelsRequest.SerializeToString,
            auth__pb2.GetDashboardPanelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDashboardPanel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateDashboardPanel',
            auth__pb2.CreateDashboardPanelRequest.SerializeToString,
            auth__pb2.CreateDashboardPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDashboardPanel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateDashboardPanel',
            auth__pb2.UpdateDashboardPanelRequest.SerializeToString,
            auth__pb2.UpdateDashboardPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDashboardPanel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteDashboardPanel',
            auth__pb2.DeleteDashboardPanelRequest.SerializeToString,
            auth__pb2.DeleteDashboardPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListNotifications',
            auth__pb2.ListNotificationsRequest.SerializeToString,
            auth__pb2.ListNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnreadNotificationCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUnreadNotificationCount',
            auth__pb2.GetUnreadNotificationCountRequest.SerializeToString,
            auth__pb2.GetUnreadNotificationCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkNotificationRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/MarkNotificationRead',
            auth__pb2.MarkNotificationReadRequest.SerializeToString,
            auth__pb2.MarkNotificationReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAllNotificationsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/MarkAllNotificationsRead',
            auth__pb2.MarkAllNotificationsReadRequest.SerializeToString,
            auth__pb2.MarkAllNotificationsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteNotification',
            auth__pb2.DeleteNotificationRequest.SerializeToString,
            auth__pb2.DeleteNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateNotification',
            auth__pb2.CreateNotificationRequest.SerializeToString,
            auth__pb2.CreateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlertRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListAlertRules',
            auth__pb2.ListAlertRulesRequest.SerializeToString,
            auth__pb2.ListAlertRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetAlertRule',
            auth__pb2.GetAlertRuleRequest.SerializeToString,
            auth__pb2.GetAlertRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlertRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateAlertRule',
            auth__pb2.CreateAlertRuleRequest.SerializeToString,
            auth__pb2.CreateAlertRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlertRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateAlertRule',
            auth__pb2.UpdateAlertRuleRequest.SerializeToString,
            auth__pb2.UpdateAlertRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlertRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteAlertRule',
            auth__pb2.DeleteAlertRuleRequest.SerializeToString,
            auth__pb2.DeleteAlertRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlertChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListAlertChannels',
            auth__pb2.ListAlertChannelsRequest.SerializeToString,
            auth__pb2.ListAlertChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetAlertChannel',
            auth__pb2.GetAlertChannelRequest.SerializeToString,
            auth__pb2.GetAlertChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlertChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateAlertChannel',
            auth__pb2.CreateAlertChannelRequest.SerializeToString,
            auth__pb2.CreateAlertChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlertChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateAlertChannel',
            auth__pb2.UpdateAlertChannelRequest.SerializeToString,
            auth__pb2.UpdateAlertChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlertChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteAlertChannel',
            auth__pb2.DeleteAlertChannelRequest.SerializeToString,
            auth__pb2.DeleteAlertChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertNotificationPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetAlertNotificationPreferences',
            auth__pb2.GetAlertNotificationPreferencesRequest.SerializeToString,
            auth__pb2.GetAlertNotificationPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertAlertNotificationPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpsertAlertNotificationPreference',
            auth__pb2.UpsertAlertNotificationPreferenceRequest.SerializeToString,
            auth__pb2.UpsertAlertNotificationPreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
